version: '3.9'

services:
  app:
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: ${USER}
        uid: ${UID}
    image: hyperf-skeleton
    container_name: hyperf-skeleton-app
    restart: unless-stopped
    working_dir: /app/
    volumes: 
      - ./:/app
    ports:
      - 9501:9501
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]